# Generated by Django 4.2.1 on 2023-07-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.IntegerField()),
                ('destini', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('phno', models.IntegerField()),
            ],
        ),
    ]
